### ISSUE TITLE
updating to the latest version of xamarin forms, seems to have messed up something

### ISSUE THREAD

**Issue by TalismanicMind** [CrossGeeks/FirebasePushNotificationPlugin#31]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
update to the latest version of xamarin forms

### Expected Behavior
successfully re/build solution

### Actual Behavior
Can't resolve the reference 'System.Void Firebase.Analytics.App::Configure()', referenced from the method 'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager/<Initialize>d__31::MoveNext()' in 'Firebase.Analytics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	Insider.iOS			

### Screenshots
![image](https://user-images.githubusercontent.com/30126543/31015656-225045aa-a519-11e7-9a11-d83dfa19cba5.png)

**Comment by TalismanicMind** [comment]
to note, i was successfully sending notification to both, android and ios development phone before this

**Comment by rdelrosario** [comment]
This doesn't seem to be an issue related to the plugin is more related to the references or your project seems are messed up. Try the following:

- Delete bin and obj folders
- Clean project
- Delete packages folder
- Close project if opened
- Reopen  project and restore packages

**Comment by TalismanicMind** [comment]
tried that still no luck! really confused, only difference between today and the last time i opened vs is updating xamarin forms

**Comment by pinheirolucas** [comment]
Same error here.

**Comment by rdelrosario** [comment]
Are you using mac or windows?

**Comment by pinheirolucas** [comment]
Windows

**Comment by TalismanicMind** [comment]
windows, (downgrading xamarin forms didnt help either)

**Comment by rdelrosario** [comment]
Updated the sample to latest forms version and compiles without issues:

https://www.dropbox.com/s/b7wg3rt8yew01v4/FirebasePushSample.zip?dl=0

Do clean once you open and restore packages, should compile fine. So your issue seems to e related to reference, check on the .csproj if there's still any reference related to an old Xamarin Forms version if so remove the old one and keep just the new one.

**Comment by rdelrosario** [comment]
For example in your .csproj, see if you got old xamarin forms version references like on this image:

![2017-09-29](https://user-images.githubusercontent.com/2547751/31021061-b55ce914-a502-11e7-942f-5e35c8c40516.png)

If so remove all the lines related to the old forms references, for the case of the image above would be all the lines that has Xamarin.Forms.2.3.4.247

**Comment by TalismanicMind** [comment]
ok will give a go thanks

**Comment by TalismanicMind** [comment]
still no luck, although i do believe you are correct, dont think the core issue is that plugin, very kind the help you have offered so far. will try removing the packages again and see from there. hopefully my hair isn't white at the end of the day

**Comment by pinheirolucas** [comment]
I've fixed the error here. 
Apparently the problem wasn't the Xamarin.Forms version.
The problem was fixed in my project downgrading the following dependencies:
- Xamarin.Firebase.iOS.Analytics: 3.6.0.2;
- Xamarin.Firebase.iOS.CloudMessaging: 1.2.1.3;
- Xamarin.Firebase.iOS.Core: 3.4.6;
- Xamarin.Firebase.iOS.InstanceID: 1.0.8.1;

@TalismanicMind hope this resolves your problem :)

**Comment by TalismanicMind** [comment]
thanks mate, your a star!

**Comment by TalismanicMind** [comment]
@pinheirolucas thanks mate!

**Comment by eyacoub** [comment]
is there any update regarding this issue? will a new version be released to fix it?
i have downgraded the libraries but i'm still getting the same issue

**Comment by rdelrosario** [comment]
There's not official updated documentation on how to work with this new version, the actual one is still outdated referencing stuff of the old version. I did a few experimental changes based on swift documentation and samples and published a new package alpha version (is still totally untested, but if you want to give it a try go ahead), no required changes needed on the plugin setup or use. But a lot of internal stuff was changed on iOS. Here is the alpha version with the unofficial support:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.0.0-alpha

Will release an official support once documentation on this component is updated.

**Comment by rdelrosario** [comment]
Let me know if any of you guys tested the alpha package I published and if works ok for you

**Comment by TalismanicMind** [comment]
at work, will test hopefully tonight, thanks

**Comment by VictorK1902** [comment]
May I ask what version of the plugin and XF you're using?
I'm using XF 2.4.0.282 and Plugin version 1.0.4, and I'm not seeing this issue.
----
Also kinda off topic but does anyone know why sending push notification on Android only works if the device is being debugged (plugged in)? Once I stopped the debugging and hit send via Postman, the device didnt get notification; only my test iPhone got it (also not being debugged)

**Comment by rdelrosario** [comment]
@VictorK1902 You won't receive any push notifications if application is stopped while debugging, should reopen and close again for notifications to work when app closed. This is due to the application being on an unstable state when stopped while debugging.

**Comment by rdelrosario** [comment]
@eyacoub Let me know if https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.0.1-alpha worked for you.

**Comment by eyacoub** [comment]
i checked the prerelease version and its working fine on visual studio 2017, but for some reason the same it didnt work on the visual studio for mac, even though it is the same application. Any Idea?

**Comment by rdelrosario** [comment]
What issues are you having on Mac?

**Comment by eyacoub** [comment]
getting the below error:
2017-10-05 17:09:56.263 OSL.iOS[26537:1217965] Could not register the assembly 'Plugin.FirebasePushNotification': System.TypeLoadException: VTable setup of type Plugin.FirebasePushNotification.FirebasePushNotificationManager failed
  at (wrapper managed-to-native) System.RuntimeType:GetMethodsByName_native (System.RuntimeType,intptr,System.Reflection.BindingFlags,bool)
  at System.RuntimeType.GetMethodsByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.Boolean ignoreCase, System.RuntimeType reflectedType) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/corlib/ReferenceSources/RuntimeType.cs:481 
  at System.RuntimeType.GetMethodCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.CallingConventions callConv, System.Type[] types, System.Boolean allowPrefixLookup) [0x00010] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/rttype.cs:2825 
  at System.RuntimeType.GetMethods (System.Reflection.BindingFlags bindingAttr) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.0.0.0/src/mono/mcs/class/referencesource/mscorlib/system/rttype.cs:3078 
  at Registrar.DynamicRegistrar.CollectMethods (System.Type type) [0x00000] in /Users/builder/data/lanes/5024/152b654a/source/xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:226 
  at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00393] in /Users/builder/data/lanes/5024/152b654a/source/xamarin-macios/src/ObjCRuntime/Registrar.cs:1590 
  at Registrar.Registrar.RegisterAssembly (System.Reflection.Assembly assembly) [0x00097] in /Users/builder/data/lanes/5024/152b654a/source/xamarin-macios/src/ObjCRuntime/Registrar.cs:2027 
Loaded assembly: /Library/Frameworks/Xamarin.Interactive.framework/Versions/Current/Agents/Forms/iOS/Xamarin.Interactive.iOS.dll [External]
2017-10-05 17:09:56.456 OSL.iOS[26537:1218001] Xamarin.iOS: Unable to locate assembly 'Xamarin.Interactive' (culture: '')
2017-10-05 17:09:56.456 OSL.iOS[26537:1218001] Xamarin.iOS: Unable to locate assembly 'Xamarin.Interactive' (culture: '')
2017-10-05 17:09:56.457 OSL.iOS[26537:1218001] Xamarin.iOS: Unable to locate assembly 'Xamarin.Interactive' (culture: '')
2017-10-05 17:09:56.458 OSL.iOS[26537:1218001] Xamarin.iOS: Unable to locate assembly 'Xamarin.Interactive' (culture: '')
Loaded assembly: /Library/Frameworks/Xamarin.Interactive.framework/Versions/Current/Agents/Forms/iOS/Xamarin.Interactive.dll [External]
Resolved pending breakpoint at 'AppDelegate.cs:27,1' to bool OSL.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00007].

**Comment by rdelrosario** [comment]
What forms version are you using? I think the issue might be related to .NET Standard support.

If using Xamarin.Forms 2.4.0:

This is on the release notes:

".NET Standard support does not work completely with Visual Studio for Mac. We highly recommend waiting for an update and service release. The work to improve this support is being tracked here."

Reference: https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.4/2.4.0-stable/

**Comment by eyacoub** [comment]
not using .Net standard still using PCL, and by the way same application(same version of everything) im trying on both visual studio.

**Comment by rdelrosario** [comment]
This plugin uses has .NETStandard support so that might the issue there.

**Comment by eyacoub** [comment]
if i understand you correctly, your saying that we should use .NETStandard for the latest version 2.0.1 Alfa?

**Comment by eyacoub** [comment]
please ignore the issue on visual studio for mac, after removing and adding again the solution and downloading all the packages, it worked again.

**Comment by rdelrosario** [comment]
oh great glad to hear that!. Well will close this issue, if anyone still experiences any other problem just open a new one, more than willing to help!

**Comment by arjunkr92** [comment]
Had same issue upgrading to v2.0.1-alpha fixed it for me.
