### ISSUE TITLE
I broke iOS push notifications, what am I doing wrong?

### ISSUE THREAD

**Issue by michaldivis** [CrossGeeks/FirebasePushNotificationPlugin#419]
Hi, I'm having a hard time getting the push notifications to work on iOS. It **worked for a while**, but then **stopped working after some seemingly unrelated changes**. Currently, it doesn't matter what payload I try to send, the iOS app doesn't seem to respond to it in any way, whether it's in foreground, background or completely killed. Please **let me know if I'm missing something**.

### GoogleService-Info.plist
Add GoogleService-Info.plist to the iOS project and set it's build action is `BundleResource`. (`Copy to Output Directory` is set to `Do not copy`, not sure if that matters).

### Enabled remote notifications
Enabled remote notification background mode in Info.plist:
```xml
<key>UIBackgroundModes</key>
<array>
    <string>remote-notification</string>
</array>
```

### Add FirebaseAppDelegateProxyEnabled
Added FirebaseAppDelegateProxyEnabled in the app’s Info.plist file and set it to No:
```xml
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
```

### Initialize the plugin
Initialized the plugin in the `FinishedLaunching` in AppDelegate.cs:
```csharp
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    //code removed for brevity...

    LoadApplication(Startup.BuildApp(ConfigureIosServices));

    FirebasePushNotificationManager.Initialize(options, true);

    return base.FinishedLaunching(app, options);
}
```

### Overrides in AppDelegate
Added the following overrides to AppDelegate.cs
```csharp
public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
{
    FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
}

public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
{
    FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
}

public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
{
    FirebasePushNotificationManager.DidReceiveMessage(userInfo);
    completionHandler(UIBackgroundFetchResult.NewData);
}
```

### Subscribe to topics and events
Subscribed to topics and subscribed to events in the `OnStartup` method in App.xaml.cs
```csharp
protected override async void OnStart()
{
    //code removed for brevity...

    //subscribe to multiple topics
    CrossFirebasePushNotification.Current.Subscribe("general");
    CrossFirebasePushNotification.Current.Subscribe("articles");
    CrossFirebasePushNotification.Current.Subscribe("discussions");

    //subscribe to push notification events
    CrossFirebasePushNotification.Current.OnNotificationError += async (s, e) =>
    {
        await MainThread.InvokeOnMainThreadAsync(() => _customPushHandler.HandleErrorAsync(e));
    };

    CrossFirebasePushNotification.Current.OnTokenRefresh += (s, e) =>
    {
        _customPushHandler.HandleTokenRefresh(e);
    };

    CrossFirebasePushNotification.Current.OnNotificationReceived += async (s, p) =>
    {
        await MainThread.InvokeOnMainThreadAsync(() => _customPushHandler.HandleAsync(p.Data, true));
    };

    CrossFirebasePushNotification.Current.OnNotificationOpened += async (s, p) =>
    {
        await MainThread.InvokeOnMainThreadAsync(() => _customPushHandler.HandleAsync(p.Data, false));
    };

    CrossFirebasePushNotification.Current.OnNotificationAction += async (s, p) =>
    {
        await MainThread.InvokeOnMainThreadAsync(() => _customPushHandler.HandleAsync(p.Data, false));
    };

    CrossFirebasePushNotification.Current.OnNotificationDeleted += (s, p) =>
    {
        _customPushHandler.HandleDeleted(p);
    };
}
```

### Notification payload
Here's an example of a payload I'm sending:

URL: https://fcm.googleapis.com/fcm/send

HTTP Method: `POST`

Headers:
- Content-Type: application/json
- Authorization: key={my-fcm-server-key}

```json
{
    "to": "/topics/general",
    "notification":{
        "body" : "General notification: Some notification text",
        "title": "MyAppName",
        "sound" : "default"
    },
    "data":{
        "appActionType": "show-general-message",
        "appActionParameter": "Some notification text"
    }
}
```

I've also tried adding a combination of these in the payload:
```json
"content_available": true
```
```json
"priority" : "high"
```

## Project settings
Here's a list of my project settings

### Used nuget packages
- Plugin.FirebasePushNotification v3.4.1
- Xamarin.Forms v5.0.0.2337

### iOS build settings
![image](https://user-images.githubusercontent.com/45868547/157634154-c81a7413-ebca-4e2e-8823-0ed7d801f505.png)

### iOS linker skip assemblies
Assemblies that the linker should skip (specified via a LinkDescription linker config file).

linker.config
```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
	<!--Attemt to fix push notifications-->
	<assembly fullname="Firebase.CloudMessaging">
		<type fullname="*" />
	</assembly>
	<assembly fullname="Firebase.Core">
		<type fullname="*" />
	</assembly>
	<assembly fullname="Firebase.Installations">
		<type fullname="*" />
	</assembly>
	<assembly fullname="Firebase.InstanceID">
		<type fullname="*" />
	</assembly>
	<assembly fullname="Plugin.FirebasePushNotification">
		<type fullname="*" />
	</assembly>
</linker>
```

Thanks for any advice!

**Comment by Hamittrpn** [comment]
I have the same problem :(

**Comment by concer22** [comment]
You are probably missing the required APN auth key (i had the same problem, after creating the key it started working). See: https://developer.clevertap.com/docs/how-to-create-an-ios-apns-auth-key

**Comment by michaldivis** [comment]
Hey @concer22 thanks for the advice! I actually did have both the APNs auth key and certificates uploaded to Firebase, so I didn't think that could be the problem. However, I've created a new auth key and a new certificate to be sure. Once I've replaced the previous APNs key and certificate in Firebase, the notifications started working again. I'm not sure what's been the problem, but it seems to be working now, so thank you!

**Comment by Hamittrpn** [comment]
After I wrote all the code as in _"Getting Started"_ my iOS project was crashing on first boot. It didn't say anything as an error message either. I finally found the solution to the problem. After installing this plugin, I solved my error by adding the **Xamarin.Firebase.InstanceID** and **Xamarin.Firebase.CloudMessaging** packages that it specified as dependency to the iOS project. 

Also I was using Xamarin.Firebase.iOS.Analytics package in my project. **Firebase.Core.App.Configure()** in AppDelegate when using this package; I fixed all the problems by commenting the code as well. If your iOS platform terminates at application launch in your Xamarin project, you can solve the problem by doing these. I already created an issue about it.

**Comment by vsimplea** [comment]
> Hey @concer22 thanks for the advice! I actually did have both the APNs auth key and certificates uploaded to Firebase, so I didn't think that could be the problem. However, I've created a new auth key and a new certificate to be sure. Once I've replaced the previous APNs key and certificate in Firebase, the notifications started working again. I'm not sure what's been the problem, but it seems to be working now, so thank you!

I'm facing the exact same issue you faced using the same settings and steps you did. However, even after recreate the APNs Key and certificate and updated them on Firebase, the notifications are still not working :(

The iOS app registers correctly and subscribes to the topic, however, I'm still not getting the notifications on iOS.

Anybody faced this issue recently?

**Comment by pmoran1947** [comment]
I have also thi issue. Notifications are being received normally on devices with iOS versions less than 15, but on iOS 15 devices no notifications are being received.
