### ISSUE TITLE
Unsubscribe is not working

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#56]
Hello @rdelrosario 

I'm back...

When I  subscribe to a topic it works perfect, I can send to that topic

        CrossFirebasePushNotification.Current.Subscribe("t_en_US");

I unsubscribe to that topic and subscribe to a new one

        CrossFirebasePushNotification.Current.Unsubscribe("t_en_US");

        CrossFirebasePushNotification.Current.Subscribe("t_es_MX");

I can send to the new one 't_es_MX'

but when I send notifications to the unsubscribed topic 't_en_US' I still receive notifications to that topic

What am I missing?

**Comment by rdelrosario** [comment]
iOs or Android?

**Comment by rubenc57** [comment]
I have been testing this in android

**Comment by rubenc57** [comment]
I'm testing in a simulator, I will test in iOS

**Comment by rdelrosario** [comment]
Can you test on a real device instead?

**Comment by rubenc57** [comment]
Ok, I'm on it

**Comment by rubenc57** [comment]
Unsubscribe in iOS in physical device is working dandy...
I will test in android

**Comment by rubenc57** [comment]
Ok, testing in android device, unsubscribing working
But still have an issue, if I kill the app and run it again the app crashes...
Still don't know why...

**Comment by rdelrosario** [comment]
Are you killing it while debugging?

**Comment by rubenc57** [comment]
Nop, I'm installing from beta testing at google play

**Comment by rubenc57** [comment]
Do you think is safe to update to xamarin last release? (4.7.10.33) 
Asking about your plugin

**Comment by rubenc57** [comment]
This is the reason why it is crashing:

        CrossFirebasePushNotification.Current.UnsubscribeAll();

Steps to reproduce:
Happens on an **android 6.0 - api 23**
Install app
run it... it woks
close it and kill it
run it again and it will crash

I run

         CrossFirebasePushNotification.Current.UnsubscribeAll(); 

in OnStart()

**Comment by rubenc57** [comment]
Maybe I don't fully understand the subscribing process
Do I unsubscribe all topics and subscribe all all topics every time I run the app? 
Only the first time?
Can I do a subscribe / unsubscribe process any time with a single topic?

**Comment by rdelrosario** [comment]
Ok please, when you run it the second time debug, so that you can put me the crash log here. Anyways not sure why you are unsubscribing each time on OnStart, subscription is persistent so you don't need to keep subscribing each time to open the app

Yes, you can subscribe/unsubscribe to a single topic anytime.

**Comment by rubenc57** [comment]
I'm not using UnsubscribeAll anymore, but I'm curious about the error:

![error](https://user-images.githubusercontent.com/20931876/32410646-381244a2-c183-11e7-8d32-6b49bd3c250f.png)

**Comment by rdelrosario** [comment]
Can you press break and copy me the application output? That will be helpful ro check what’s it about

**Comment by rubenc57** [comment]
device log:
[error.txt](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1444159/error.txt)

**Comment by rdelrosario** [comment]
That didn't seem to say much about the issue, maybe if you click Continue instead of break we get better logs.

**Comment by rubenc57** [comment]
[error2.txt](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1444667/error2.txt)

**Comment by rdelrosario** [comment]
Ok thanks. Issue should be fixed on: 

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.1-beta

This version also has localization support. Docs on localization here:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/localization-support/docs/LocalizedFirebasePushNotifications.md

**Comment by rubenc57** [comment]
Thanks

**Comment by rubenc57** [comment]
Do you have any suggestions  how to send local notifications?

**Comment by rdelrosario** [comment]
Yes you can install, if you run into any issues just let me know.

About local notifications:

https://github.com/aritchie/notifications

**Comment by rubenc57** [comment]
Thanks, I will update

I don't know why I still have problems unsubscribing in iOS and android
for example, I subscribe once to these topics:
't_android'
't_general'
't_es'

and execute this code:

                string[]subTopics =  CrossFirebasePushNotification.Current.SubscribedTopics;

and get the topics list fine

then i unsubscribe from 't_es' and subscribe to 't_en' with this code:

                CrossFirebasePushNotification.Current.Unsubscribe("t_es");
                CrossFirebasePushNotification.Current.Subscribe("t_en");

Get the topics list again and the list is updated, I send to the new topic 't_en' and receive notifications

                condition = 't_android' in topics && 't_en' in topics

but if I  send to 't_es' still receive notifications:

                condition = 't_android' in topics && 't_es' in topics

What am I missing?

**Comment by rdelrosario** [comment]
Maybe it might take a few minutes, what time span you tested between unsubscribing and sending the push?

**Comment by rubenc57** [comment]
right away

**Comment by rubenc57** [comment]
I sent again after 5 hours and still get them

**Comment by rubenc57** [comment]
I also have noticed that if I don't subscribe again to the topics I'm not subscribed to them at all
They are not persistent

**Comment by rubenc57** [comment]
All these tested on a simulator, I'm testing now in a physical device

**Comment by rdelrosario** [comment]
That's because you are testing on debug, on debug subscription might not be persistent because the implementation reset the token each time you run it.

**Comment by rubenc57** [comment]
Ok I understand, thanks

**Comment by rubenc57** [comment]
Ok, I confirm that in physical devices, it works great

Maybe you could suggest your new users to test on physical devices

Although some of the features work on simulators

**Comment by rdelrosario** [comment]
Ok great! Are you testing on the latest version?

**Comment by rubenc57** [comment]
I'm planning to do that today, will let you know how it goes

**Comment by rubenc57** [comment]
Ok, version 2.1.1-beta works fine on android 

in iOS is falling to subscribe topics in version 11.1 (simulator) and sometimes crashes
I will test on 10.3.2 physical device

I haven't update to latest xamarin 4.7.10.33 though

**Comment by rdelrosario** [comment]
What crashes are you getting on iOS? do you have the output?

**Comment by rubenc57** [comment]
I do not have an output, It just stops running, I tried to debug but it did not give me an exception  or an error

**Comment by rdelrosario** [comment]
I weird because the change on iOS was just two lines of code. So is always crashing for you on iOS?

**Comment by rubenc57** [comment]
It only crashes in the remote simulator to windows
In the Mac simulator doesn't crash

But still **cannot** see the list of topics I'm subscribed on

I updated to latest stable xamarin and nuget plugins, it's the same

**Comment by rubenc57** [comment]
In a physical iOS device it works fine :)
It does not crash, I can see my topic list, I can receive notifications

**Comment by rdelrosario** [comment]
So the problem is when testing simulators?

Actually, push notifications doesn't work on iOS Simulators just on physical devices. So topics won't work there because it doesn't even generate a token.

So to confirm everything is working as expected on latest beta on physical devices? right? I guess we can close this issue if so.

**Comment by rubenc57** [comment]
Yes everything working as expected
Thank you for your assistant

**Comment by rubenc57** [comment]
Do you have another suggestion for local notifications?

The one you suggested has installation problem in android and apparently they are not helping in that issue
