### ISSUE TITLE
iOS get warning: FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by lvduc** [CrossGeeks/FirebasePushNotificationPlugin#80]
## Bug Information

Version Number of Plugin: 2.1.3
Device Tested On: iPhone 6, iOS 11
Simulator Tested On:
Version of VS: Community 2017 15.4.1
Version of Xamarin: 4.7.10.22
Versions of other things you are using: Xamarin.iOS and Xamarin.Mac SDK 11.2.0.8

### Expected Behavior
Get notification
### Actual Behavior
Nothing happen
### Screenshots

The iOS app worked well in last week. But it cannot work from Monday. The Android app still works well. I try to update NuGet packages which related with Firebase but nothing changes.

When I send a notification, the console debug display:
2017-12-13 19:21:21.881 EPaging.iOS[2334] <Warning> [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

Please help me.

Many thanks

**Comment by lvduc** [comment]
Oh, I fixed it. Maybe Info.plist have some bad character when saving in Window. My app work again with the Info.plist saved in Mac.

I resolve the warning by adding 
        [Export("messaging:didReceiveMessage:")]
        public void DidReceiveMessage(Firebase.CloudMessaging.Messaging messaging, Firebase.CloudMessaging.RemoteMessage remoteMessage)
        {
            Console.WriteLine(remoteMessage.AppData);
            FirebasePushNotificationManager.DidReceiveMessage(remoteMessage.AppData);
        }

But I don't know if it is needed or not.

Thanks

**Comment by rdelrosario** [comment]
mmm this shouldn't be needed actually plugin implements this method internally.

**Comment by nemexyz** [comment]
@lvduc how did you do to implement the function in AppDelegate? I have the same problem and I have not been able to solve it because something is missing internally.

**Comment by pisipisi** [comment]
I got this issue, tried to follow your method, but didn't help. And I;m using Visual Studio in Windows, pair to Mac

**Comment by stesvis** [comment]
I still get this error today in 2021....the plugin version is 3.3.10

**Comment by MuhammadJazab** [comment]
facing same error
